/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    CreateNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNITest_CreateNI
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    DeleteNI
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNITest_DeleteNI
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    Print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNITest_Print
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    setSource
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNITest_setSource
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNITest
 * Method:    getSource
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    setTarget
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNITest_setTarget
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNITest
 * Method:    getTarget
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getTarget
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    setPreset
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNITest_setPreset
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNITest
 * Method:    getPreset
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getPreset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    setThumbnailTime
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_JNITest_setThumbnailTime
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     JNITest
 * Method:    getThumbnailTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_JNITest_getThumbnailTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    StartEncode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNITest_StartEncode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    StartThumbnail
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNITest_StartThumbnail
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNITest
 * Method:    Wait
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNITest_Wait
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
